window.esdocSearchIndex = [
  [
    "jumbogrove/src/jg/character.js~character",
    "class/src/jg/character.js~Character.html",
    "<span>Character</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/character.js</span>",
    "class"
  ],
  [
    "jumbogrove/src/jg/situation.js~situation",
    "class/src/jg/situation.js~Situation.html",
    "<span>Situation</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/situation.js</span>",
    "class"
  ],
  [
    "jumbogrove/src/jg/gameformat/character.js~character",
    "class/src/jg/gameformat/character.js~character.html",
    "<span>character</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/gameformat/character.js</span>",
    "class"
  ],
  [
    "jumbogrove/src/jg/qualities/flag.js~flag",
    "variable/index.html#static-variable-flag",
    "<span>flag</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/flag.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/jg/qualities/fudgeadjective.js~fudgeadjective",
    "variable/index.html#static-variable-fudgeAdjective",
    "<span>fudgeAdjective</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/fudgeAdjective.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/jg/gameformat/game.js~game",
    "class/src/jg/gameformat/game.js~game.html",
    "<span>game</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/gameformat/game.js</span>",
    "class"
  ],
  [
    "jumbogrove/src/jg/qualities/integer.js~integer",
    "variable/index.html#static-variable-integer",
    "<span>integer</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/integer.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/main.js~jumbogrove",
    "function/index.html#static-function-jumbogrove",
    "<span>jumbogrove</span> <span class=\"search-result-import-path\">jumbogrove/src/main.js</span>",
    "function"
  ],
  [
    "jumbogrove/src/jg/model.js~model",
    "class/src/jg/model.js~model.html",
    "<span>model</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/model.js</span>",
    "class"
  ],
  [
    "jumbogrove/src/jg/qualities/namedchoice.js~namedchoice",
    "variable/index.html#static-variable-namedChoice",
    "<span>namedChoice</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/namedChoice.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/jg/qualities/nonzerointeger.js~nonzerointeger",
    "variable/index.html#static-variable-nonZeroInteger",
    "<span>nonZeroInteger</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/nonZeroInteger.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/jg/qualities/onoff.js~onoff",
    "variable/index.html#static-variable-onOff",
    "<span>onOff</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/onOff.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/jg/qualities/index.js~qualities",
    "variable/index.html#static-variable-qualities",
    "<span>qualities</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/index.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/jg/qualities/raw.js~raw",
    "variable/index.html#static-variable-raw",
    "<span>raw</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/raw.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/jg/gameformat/situation.js~situation",
    "class/src/jg/gameformat/situation.js~situation.html",
    "<span>situation</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/gameformat/situation.js</span>",
    "class"
  ],
  [
    "jumbogrove/src/jg/dataui.js~ui",
    "class/src/jg/dataui.js~ui.html",
    "<span>ui</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/dataui.js</span>",
    "class"
  ],
  [
    "jumbogrove/src/jg/qualities/wordscale.js~wordscale",
    "variable/index.html#static-variable-wordScale",
    "<span>wordScale</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/wordScale.js</span>",
    "variable"
  ],
  [
    "jumbogrove/src/jg/qualities/yesno.js~yesno",
    "variable/index.html#static-variable-yesNo",
    "<span>yesNo</span> <span class=\"search-result-import-path\">jumbogrove/src/jg/qualities/yesNo.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/example.js",
    "file/src/example.js.html",
    "src/example.js",
    "file"
  ],
  [
    "src/example2.js",
    "file/src/example2.js.html",
    "src/example2.js",
    "file"
  ],
  [
    "src/jg/character.js",
    "file/src/jg/character.js.html",
    "src/jg/character.js",
    "file"
  ],
  [
    "src/jg/character.js~character#_shallowqualities",
    "class/src/jg/character.js~Character.html#instance-member-_shallowQualities",
    "src/jg/character.js~Character#_shallowQualities",
    "member"
  ],
  [
    "src/jg/character.js~character#addtoquality",
    "class/src/jg/character.js~Character.html#instance-method-addToQuality",
    "src/jg/character.js~Character#addToQuality",
    "method"
  ],
  [
    "src/jg/character.js~character#constructor",
    "class/src/jg/character.js~Character.html#instance-constructor-constructor",
    "src/jg/character.js~Character#constructor",
    "method"
  ],
  [
    "src/jg/character.js~character#formatquality",
    "class/src/jg/character.js~Character.html#instance-method-formatQuality",
    "src/jg/character.js~Character#formatQuality",
    "method"
  ],
  [
    "src/jg/character.js~character#formatqualityname",
    "class/src/jg/character.js~Character.html#instance-method-formatQualityName",
    "src/jg/character.js~Character#formatQualityName",
    "method"
  ],
  [
    "src/jg/character.js~character#getquality",
    "class/src/jg/character.js~Character.html#instance-method-getQuality",
    "src/jg/character.js~Character#getQuality",
    "method"
  ],
  [
    "src/jg/character.js~character#getqualityinitial",
    "class/src/jg/character.js~Character.html#instance-method-getQualityInitial",
    "src/jg/character.js~Character#getQualityInitial",
    "method"
  ],
  [
    "src/jg/character.js~character#id",
    "class/src/jg/character.js~Character.html#instance-member-id",
    "src/jg/character.js~Character#id",
    "member"
  ],
  [
    "src/jg/character.js~character#name",
    "class/src/jg/character.js~Character.html#instance-member-name",
    "src/jg/character.js~Character#name",
    "member"
  ],
  [
    "src/jg/character.js~character#setquality",
    "class/src/jg/character.js~Character.html#instance-method-setQuality",
    "src/jg/character.js~Character#setQuality",
    "method"
  ],
  [
    "src/jg/character.js~character#state",
    "class/src/jg/character.js~Character.html#instance-member-state",
    "src/jg/character.js~Character#state",
    "member"
  ],
  [
    "src/jg/commands.js",
    "file/src/jg/commands.js.html",
    "src/jg/commands.js",
    "file"
  ],
  [
    "src/jg/dataui.js",
    "file/src/jg/dataui.js.html",
    "src/jg/dataui.js",
    "file"
  ],
  [
    "src/jg/dataui.js~markdownit",
    "https://github.com/markdown-it/markdown-it",
    "src/jg/dataui.js~MarkdownIt",
    "external"
  ],
  [
    "src/jg/dataui.js~ui#addtemplatecontext",
    "class/src/jg/dataui.js~ui.html#instance-method-addTemplateContext",
    "src/jg/dataui.js~ui#addTemplateContext",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#addtemplategetters",
    "class/src/jg/dataui.js~ui.html#instance-method-addTemplateGetters",
    "src/jg/dataui.js~ui#addTemplateGetters",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#createtemplate",
    "class/src/jg/dataui.js~ui.html#instance-member-createTemplate",
    "src/jg/dataui.js~ui#createTemplate",
    "member"
  ],
  [
    "src/jg/dataui.js~ui#director",
    "class/src/jg/dataui.js~ui.html#instance-member-director",
    "src/jg/dataui.js~ui#director",
    "member"
  ],
  [
    "src/jg/dataui.js~ui#md",
    "class/src/jg/dataui.js~ui.html#instance-member-md",
    "src/jg/dataui.js~ui#md",
    "member"
  ],
  [
    "src/jg/dataui.js~ui#nunjucks",
    "class/src/jg/dataui.js~ui.html#instance-member-nunjucks",
    "src/jg/dataui.js~ui#nunjucks",
    "member"
  ],
  [
    "src/jg/dataui.js~ui#presentchoices",
    "class/src/jg/dataui.js~ui.html#instance-method-presentChoices",
    "src/jg/dataui.js~ui#presentChoices",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#promptinput",
    "class/src/jg/dataui.js~ui.html#instance-method-promptInput",
    "src/jg/dataui.js~ui#promptInput",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#rendermarkdown",
    "class/src/jg/dataui.js~ui.html#instance-method-renderMarkdown",
    "src/jg/dataui.js~ui#renderMarkdown",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#rendermarkdowntemplate",
    "class/src/jg/dataui.js~ui.html#instance-method-renderMarkdownTemplate",
    "src/jg/dataui.js~ui#renderMarkdownTemplate",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#rendermarkdowntemplatemaybeinline",
    "class/src/jg/dataui.js~ui.html#instance-method-renderMarkdownTemplateMaybeInline",
    "src/jg/dataui.js~ui#renderMarkdownTemplateMaybeInline",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#rendertemplate",
    "class/src/jg/dataui.js~ui.html#instance-method-renderTemplate",
    "src/jg/dataui.js~ui#renderTemplate",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#writehtml",
    "class/src/jg/dataui.js~ui.html#instance-method-writeHTML",
    "src/jg/dataui.js~ui#writeHTML",
    "method"
  ],
  [
    "src/jg/dataui.js~ui#writemarkdown",
    "class/src/jg/dataui.js~ui.html#instance-method-writeMarkdown",
    "src/jg/dataui.js~ui#writeMarkdown",
    "method"
  ],
  [
    "src/jg/director.js",
    "file/src/jg/director.js.html",
    "src/jg/director.js",
    "file"
  ],
  [
    "src/jg/gameformat/character.js",
    "file/src/jg/gameformat/character.js.html",
    "src/jg/gameformat/character.js",
    "file"
  ],
  [
    "src/jg/gameformat/game.js",
    "file/src/jg/gameformat/game.js.html",
    "src/jg/gameformat/game.js",
    "file"
  ],
  [
    "src/jg/gameformat/game.js~game#asideheader",
    "class/src/jg/gameformat/game.js~game.html#instance-member-asideHeader",
    "src/jg/gameformat/game.js~game#asideHeader",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#autoscroll",
    "class/src/jg/gameformat/game.js~game.html#instance-member-autoScroll",
    "src/jg/gameformat/game.js~game#autoScroll",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#characters",
    "class/src/jg/gameformat/game.js~game.html#instance-member-characters",
    "src/jg/gameformat/game.js~game#characters",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#defaultstylesheet",
    "class/src/jg/gameformat/game.js~game.html#instance-member-defaultStylesheet",
    "src/jg/gameformat/game.js~game#defaultStylesheet",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#didact",
    "class/src/jg/gameformat/game.js~game.html#instance-method-didAct",
    "src/jg/gameformat/game.js~game#didAct",
    "method"
  ],
  [
    "src/jg/gameformat/game.js~game#didenter",
    "class/src/jg/gameformat/game.js~game.html#instance-method-didEnter",
    "src/jg/gameformat/game.js~game#didEnter",
    "method"
  ],
  [
    "src/jg/gameformat/game.js~game#didexit",
    "class/src/jg/gameformat/game.js~game.html#instance-method-didExit",
    "src/jg/gameformat/game.js~game#didExit",
    "method"
  ],
  [
    "src/jg/gameformat/game.js~game#globalstate",
    "class/src/jg/gameformat/game.js~game.html#instance-member-globalState",
    "src/jg/gameformat/game.js~game#globalState",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#id",
    "class/src/jg/gameformat/game.js~game.html#instance-member-id",
    "src/jg/gameformat/game.js~game#id",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#init",
    "class/src/jg/gameformat/game.js~game.html#instance-method-init",
    "src/jg/gameformat/game.js~game#init",
    "method"
  ],
  [
    "src/jg/gameformat/game.js~game#initialsituation",
    "class/src/jg/gameformat/game.js~game.html#instance-member-initialSituation",
    "src/jg/gameformat/game.js~game#initialSituation",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#navheader",
    "class/src/jg/gameformat/game.js~game.html#instance-member-navHeader",
    "src/jg/gameformat/game.js~game#navHeader",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#showaside",
    "class/src/jg/gameformat/game.js~game.html#instance-member-showAside",
    "src/jg/gameformat/game.js~game#showAside",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#shownav",
    "class/src/jg/gameformat/game.js~game.html#instance-member-showNav",
    "src/jg/gameformat/game.js~game#showNav",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#situations",
    "class/src/jg/gameformat/game.js~game.html#instance-member-situations",
    "src/jg/gameformat/game.js~game#situations",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#version",
    "class/src/jg/gameformat/game.js~game.html#instance-member-version",
    "src/jg/gameformat/game.js~game#version",
    "member"
  ],
  [
    "src/jg/gameformat/game.js~game#willact",
    "class/src/jg/gameformat/game.js~game.html#instance-method-willAct",
    "src/jg/gameformat/game.js~game#willAct",
    "method"
  ],
  [
    "src/jg/gameformat/game.js~game#willenter",
    "class/src/jg/gameformat/game.js~game.html#instance-method-willEnter",
    "src/jg/gameformat/game.js~game#willEnter",
    "method"
  ],
  [
    "src/jg/gameformat/game.js~game#willexit",
    "class/src/jg/gameformat/game.js~game.html#instance-method-willExit",
    "src/jg/gameformat/game.js~game#willExit",
    "method"
  ],
  [
    "src/jg/gameformat/situation.js",
    "file/src/jg/gameformat/situation.js.html",
    "src/jg/gameformat/situation.js",
    "file"
  ],
  [
    "src/jg/gamepad.js",
    "file/src/jg/gamepad.js.html",
    "src/jg/gamepad.js",
    "file"
  ],
  [
    "src/jg/index.js",
    "file/src/jg/index.js.html",
    "src/jg/index.js",
    "file"
  ],
  [
    "src/jg/model.js",
    "file/src/jg/model.js.html",
    "src/jg/model.js",
    "file"
  ],
  [
    "src/jg/model.js~model#allcharacters",
    "class/src/jg/model.js~model.html#instance-member-allCharacters",
    "src/jg/model.js~model#allCharacters",
    "member"
  ],
  [
    "src/jg/model.js~model#character",
    "class/src/jg/model.js~model.html#instance-method-character",
    "src/jg/model.js~model#character",
    "method"
  ],
  [
    "src/jg/model.js~model#currentsituation",
    "class/src/jg/model.js~model.html#instance-member-currentSituation",
    "src/jg/model.js~model#currentSituation",
    "member"
  ],
  [
    "src/jg/model.js~model#do",
    "class/src/jg/model.js~model.html#instance-method-do",
    "src/jg/model.js~model#do",
    "method"
  ],
  [
    "src/jg/model.js~model#extend",
    "class/src/jg/model.js~model.html#instance-method-extend",
    "src/jg/model.js~model#extend",
    "method"
  ],
  [
    "src/jg/model.js~model#globalstate",
    "class/src/jg/model.js~model.html#instance-member-globalState",
    "src/jg/model.js~model#globalState",
    "member"
  ],
  [
    "src/jg/model.js~model#goto",
    "class/src/jg/model.js~model.html#instance-method-goTo",
    "src/jg/model.js~model#goTo",
    "method"
  ],
  [
    "src/jg/model.js~model#interpretchoices",
    "class/src/jg/model.js~model.html#instance-method-interpretChoices",
    "src/jg/model.js~model#interpretChoices",
    "method"
  ],
  [
    "src/jg/model.js~model#ismanagedlink",
    "class/src/jg/model.js~model.html#instance-method-isManagedLink",
    "src/jg/model.js~model#isManagedLink",
    "method"
  ],
  [
    "src/jg/model.js~model#player",
    "class/src/jg/model.js~model.html#instance-member-player",
    "src/jg/model.js~model#player",
    "member"
  ],
  [
    "src/jg/model.js~model#random",
    "class/src/jg/model.js~model.html#instance-method-random",
    "src/jg/model.js~model#random",
    "method"
  ],
  [
    "src/jg/model.js~model#situation",
    "class/src/jg/model.js~model.html#instance-method-situation",
    "src/jg/model.js~model#situation",
    "method"
  ],
  [
    "src/jg/model.js~model#situations",
    "class/src/jg/model.js~model.html#instance-method-situations",
    "src/jg/model.js~model#situations",
    "method"
  ],
  [
    "src/jg/qualities/flag.js",
    "file/src/jg/qualities/flag.js.html",
    "src/jg/qualities/flag.js",
    "file"
  ],
  [
    "src/jg/qualities/fudgeadjective.js",
    "file/src/jg/qualities/fudgeAdjective.js.html",
    "src/jg/qualities/fudgeAdjective.js",
    "file"
  ],
  [
    "src/jg/qualities/index.js",
    "file/src/jg/qualities/index.js.html",
    "src/jg/qualities/index.js",
    "file"
  ],
  [
    "src/jg/qualities/integer.js",
    "file/src/jg/qualities/integer.js.html",
    "src/jg/qualities/integer.js",
    "file"
  ],
  [
    "src/jg/qualities/namedchoice.js",
    "file/src/jg/qualities/namedChoice.js.html",
    "src/jg/qualities/namedChoice.js",
    "file"
  ],
  [
    "src/jg/qualities/nonzerointeger.js",
    "file/src/jg/qualities/nonZeroInteger.js.html",
    "src/jg/qualities/nonZeroInteger.js",
    "file"
  ],
  [
    "src/jg/qualities/onoff.js",
    "file/src/jg/qualities/onOff.js.html",
    "src/jg/qualities/onOff.js",
    "file"
  ],
  [
    "src/jg/qualities/raw.js",
    "file/src/jg/qualities/raw.js.html",
    "src/jg/qualities/raw.js",
    "file"
  ],
  [
    "src/jg/qualities/wordscale.js",
    "file/src/jg/qualities/wordScale.js.html",
    "src/jg/qualities/wordScale.js",
    "file"
  ],
  [
    "src/jg/qualities/yesno.js",
    "file/src/jg/qualities/yesNo.js.html",
    "src/jg/qualities/yesNo.js",
    "file"
  ],
  [
    "src/jg/situation.js",
    "file/src/jg/situation.js.html",
    "src/jg/situation.js",
    "file"
  ],
  [
    "src/jg/situation.js~situation#constructor",
    "class/src/jg/situation.js~Situation.html#instance-constructor-constructor",
    "src/jg/situation.js~Situation#constructor",
    "method"
  ],
  [
    "src/jg/situation.js~situation#debugchoices",
    "class/src/jg/situation.js~Situation.html#instance-member-debugChoices",
    "src/jg/situation.js~Situation#debugChoices",
    "member"
  ],
  [
    "src/jg/situation.js~situation#hastag",
    "class/src/jg/situation.js~Situation.html#instance-method-hasTag",
    "src/jg/situation.js~Situation#hasTag",
    "method"
  ],
  [
    "src/jg/situation.js~situation#id",
    "class/src/jg/situation.js~Situation.html#instance-member-id",
    "src/jg/situation.js~Situation#id",
    "member"
  ],
  [
    "src/jg/situation.js~situation#tags",
    "class/src/jg/situation.js~Situation.html#instance-member-tags",
    "src/jg/situation.js~Situation#tags",
    "member"
  ],
  [
    "src/jg/situation.js~situation#totalvisits",
    "class/src/jg/situation.js~Situation.html#instance-member-totalVisits",
    "src/jg/situation.js~Situation#totalVisits",
    "member"
  ],
  [
    "src/jg/vueui.js",
    "file/src/jg/vueui.js.html",
    "src/jg/vueui.js",
    "file"
  ],
  [
    "src/main.js",
    "file/src/main.js.html",
    "src/main.js",
    "file"
  ]
]